# Config file for f110_reactive_methods package

# Lidar Scan Truncation Coverage Angle
# (Assumes symmetric coverage about the center)
truncated_coverage_angle : 3.14

# High Distance rejection threshold
max_accepted_distance : 3.0

# Ranges Smoothing Filter Size
# Dimension : 1 x (2*smoothing_filter_size-1)
smoothing_filter_size : 3

# Safety Bubble Threshold
bubble_radius : 1.0

# Steering Reactivity (towards the best point in the lidar scan)
# High steering_angle_reactivity -> Good for taking sharp turns and avoiding obstacles
# Less steering_angle_reactivity -> Better stable state behavior (Less Wobbly)
steering_angle_reactivity : 0.05

# Velocity
error_based_velocities : {low: 5.0, medium: 3.0, high: 1.5}


